openapi: 3.0.3
info:
  title: Openapi Plugin Bug
  version: 1.0.0
servers:

  - url: http://localhost:3000/
    description: Local server

paths:
  /:
    get:
      description: Index route.
      operationId: index
      responses:
        200:
          description: 200 OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  greeting:
                    type: string

